### ISSUE TITLE
Katarina passive (Voracity) doesn't trigger after kill/assist

### ISSUE THREAD

**Issue by baaannnaaannn** [brian8544/LeagueServer#26]
### Description

passive ability does not work

- reset abilities for 15 seconds

### Expected Behavior

reset abilities for 15 seconds

### Steps to Reproduce

start game with Kata
and press R

### Server Version

4.2

### Emulator Revision/Commit Hash

latest one?

### Operating System

Linux

### Custom Modifications

None

**Comment by brian8544** [comment]
Note for myself:

ApiEventManager.OnKill is seemingly broken, since replacing OnKill>OnKillUnit will make the script work. Still only triggers with minions.

ApiEventManager.OnKill must be fixed.
